import FlashSales from "@/features/home/components/FlashSales";
import Hero from "@/features/home/components/Hero";
import { Divider } from "antd";

import Services from "@/components/Services";
import ScrollTopFloatButton from "@/components/ui/ScrollTopFloatButton";
import AdvertisementBanner from "@/features/home/components/AdvertisementBanner";
import BestSellingProducts from "@/features/home/components/BestSellingProducts";
import BrowseByCategory from "@/features/home/components/BrowseByCategory";
import ExploreOurProducts from "@/features/home/components/ExploreOurProducts";
import NewArrival from "@/features/home/components/NewArrival";

import { Metadata } from "next";
import { PrismaClient } from "@prisma/client";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default async function Home() {
  const products = await prisma.product.findMany();

  return (
    <main>
      <Hero products={products} />
      <FlashSales products={products} />
      <Divider />
      <BrowseByCategory />
      <Divider />
      <BestSellingProducts products={products} />
      <AdvertisementBanner />
      <ExploreOurProducts products={products} />
      <NewArrival />
      <Services />
      <ScrollTopFloatButton />
    </main>
  );
}
