import FlashSales from "@/features/home/components/FlashSales";
import Hero from "@/features/home/components/Hero";
import { Divider } from "antd";

import AdvertisementBanner from "@/components/ui/AdvertisementBanner";
import BestSellingProducts from "@/features/home/components/BestSellingProducts";
import Categories from "@/features/home/components/Categories";
import ExploreOurProducts from "@/features/home/components/ExploreOurProducts";
import { getProducts } from "@/features/home/components/server/products";
import { Metadata } from "next";
import NewArrival from "@/features/home/components/NewArrival";
import Services from "@/features/home/components/Services";

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default async function Home() {
  const products = await getProducts();

  return (
    <main>
      <Hero />
      <FlashSales  products={products} />
      <Divider />
      <Categories />
      <Divider />
      <BestSellingProducts products={products} />
      <AdvertisementBanner />
      <ExploreOurProducts products={products} />
      <NewArrival/>
      <Services/>
    </main>
  );
}
