import FlashSales from "@/src/features/home/components/FlashSales";
import Hero from "@/src/features/home/components/Hero";
import { Divider } from "antd";

import AdvertisementBanner from "@/src/features/home/components/AdvertisementBanner";
import BestSellingProducts from "@/src/features/home/components/BestSellingProducts";
import BrowseByCategory from "@/src/features/home/components/BrowseByCategory";
import ExploreOurProducts from "@/src/features/home/components/ExploreOurProducts";
import { getProducts } from "@/src/server/products";
import { Metadata } from "next";
import NewArrival from "@/src/features/home/components/NewArrival";
import Services from "@/src/components/Services";
import ScrollTopFloatButton from "@/src/components/ui/ScrollTopFloatButton";

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default async function Home() {
  const products = await getProducts();

  return (
    <main>
      <Hero />
      <FlashSales products={products} />
      <Divider />
      <BrowseByCategory />
      <Divider />
      <BestSellingProducts products={products} />
      <AdvertisementBanner />
      <ExploreOurProducts products={products} />
      <NewArrival />
      <Services />
      <ScrollTopFloatButton />
    </main>
  );
}
